"""Add audio_sample table

Revision ID: d46097fb11fc
Revises: 4bd01c907050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46097fb11fc'
down_revision: Union[str, None] = '4bd01c907050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_sample',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('zone_offset', sa.String(length=10), nullable=True),
    sa.Column('sample_duration_sec', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('pitch_mean', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('energy_rms', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('silence_ratio', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('breathing_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('valence_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('arousal_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audio_sample_user_recorded_at', 'audio_sample', ['user_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audio_sample_user_recorded_at', table_name='audio_sample')
    op.drop_table('audio_sample')
    # ### end Alembic commands ###
