"""alter_audio_sample_add_trigger_fields_create_audio_daily_summary

Revision ID: 418b9ec4294a
Revises: d46097fb11fc

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418b9ec4294a'
down_revision: Union[str, None] = 'd46097fb11fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_daily_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('usable_count', sa.Integer(), nullable=True),
    sa.Column('skipped_count', sa.Integer(), nullable=True),
    sa.Column('avg_valence', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('avg_arousal', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('avg_pitch_mean', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('avg_energy_rms', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('avg_silence_ratio', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('avg_breathing_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_audio_daily_summary_user_date')
    )
    op.add_column('audio_sample', sa.Column('trigger', sa.String(length=32), nullable=True))
    op.add_column('audio_sample', sa.Column('ambient_db', sa.Numeric(precision=6, scale=3), nullable=True))
    op.add_column('audio_sample', sa.Column('was_skipped', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('audio_sample', sa.Column('environment_quality', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_sample', 'environment_quality')
    op.drop_column('audio_sample', 'was_skipped')
    op.drop_column('audio_sample', 'ambient_db')
    op.drop_column('audio_sample', 'trigger')
    op.drop_table('audio_daily_summary')
    # ### end Alembic commands ###
